# Generated by Django 6.0.7 on 2026-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorebharat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirm_password', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
