# Generated by Django 6.0.7 on 2026-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorebharat', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monument_name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('google_map', models.CharField(max_length=500, null=True)),
                ('short_description', models.CharField(max_length=300, null=True)),
                ('detailed_history', models.TextField(null=True)),
                ('opening_time', models.CharField(max_length=50, null=True)),
                ('closing_time', models.CharField(max_length=50, null=True)),
                ('best_time_to_visit', models.CharField(max_length=300, null=True)),
                ('travel_tips', models.TextField(null=True)),
                ('monument_image', models.ImageField(null=True, upload_to='monuments/')),
            ],
        ),
    ]
