# Generated by Django 6.0.7 on 2026-07-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorebharat', '0003_monument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorebharat.monument')),
            ],
        ),
    ]
