# Generated by Django 6.0.7 on 2026-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorebharat', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
