# Generated by Django 6.0.7 on 2026-08-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorebharat', '0005_monument_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='adult_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='monument',
            name='child_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='monument',
            name='foreign_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('adult_tickets', models.PositiveIntegerField(default=0)),
                ('child_tickets', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('booking_status', models.CharField(default='Confirmed', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorebharat.monument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorebharat.register')),
            ],
        ),
    ]
