# Generated by Django 6.0.7 on 2026-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorebharat', '0006_monument_adult_fee_monument_child_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
